ContactBook.Web/Models/AddEditContactModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ContactBook.Web.Models
{
    public class AddEditContactModel
    {
        public int Id { get; set; }


        [Required]
        [StringLength(100)]
        [RegularExpression(@"^[a-zA-Z0-9]+[a-zA-Z0-9\s-,\.]*",
                        ErrorMessage = "{0} should have an alphabet or number")]
        public string Name { get; set; }

        [DisplayName("Phone Number")]
        [Required]
        [RegularExpression(@"^(?:\+?234|0){1}[7-9]\d[1-9]\d{7}$",
                                ErrorMessage = "{0} is invalid. Enter e.g 07036833337,+2347036833337")]
        public string PhoneNumber { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Please enter a valid email e.g ayo@gmail.com")]
        [StringLength(100)]
        public string Email { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(200)]
        [RegularExpression(@"^[a-zA-Z0-9]+[a-zA-Z0-9\s-,\.]*",
                        ErrorMessage = "{0} should have an alphabet or number")]
        public string Address { get; set; }

        [Required]
        public int? ContactGroup { get; set; }

       // [DisplayName("Contact Group")]
        public string ContactGroupName { get; set; }

    }
}

ContactBook.Web/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using ContackBook.Model;
using ContackBook.Model.Persistence.Repositories;
using ContactBook.Persistence;
using ContactBook.Web.Models;

namespace ContactBook.Web.Controllers
{
    [HandleError]
    public class ContactsController : Controller
    {
        private readonly IContactRepository _contactRepository;
        public ContactsController(IContactRepository contactRepository)
        {
            _contactRepository = contactRepository;
        }

        // GET: Contacts
        public ActionResult Index()
        {
            
            var contacts = _contactRepository.GetAll();

            return View(contacts.ToList());
        }

        // GET: Contacts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var contact = await _contactRepository.Get(id.Value);
            if (contact == null)
            {
                return HttpNotFound();
            }
            var contactModel = Mapper.Map<AddEditContactModel>(contact);

            return View(contactModel);
        }

        // GET: Contacts/Create
        public ActionResult Create()
        {
            //I could use @Html.enumdropdownlistFor on the view too
            ViewBag.ContactGroup = new SelectList(GetEnumSelectList<ContactGroup>(),"Value","Text");
            return View();
        }

        // POST: Contacts/Create
        //Used View Model to guard against overPosting
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddEditContactModel model)
        {

            if (ModelState.IsValid)
            {
                var contact = Mapper.Map<Contact>(model);
                await _contactRepository.Save(contact);
                TempData["message"] = "Contact Added Successfully";
                return RedirectToAction("Index");
            }

            ViewBag.ContactGroup= new SelectList(GetEnumSelectList<ContactGroup>(), 
                                                        "Value", "Text",model.ContactGroup);
            return View(model);
        }

        // GET: Contacts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var contact = await _contactRepository.Get(id.Value);
            if (contact == null)
            {
                return HttpNotFound();
            }

            var contactModel = Mapper.Map<AddEditContactModel>(contact);

            ViewBag.ContactGroup = new SelectList(GetEnumSelectList<ContactGroup>(), 
                                                            "Value", "Text", contactModel.ContactGroup);

            
            return View(contactModel);
        }

        // POST: Contacts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AddEditContactModel model)
        {
            if (ModelState.IsValid)
            {
                var contact = Mapper.Map<Contact>(model);
                await _contactRepository.Update(contact);
                TempData["message"] = "Contact Edited Successfully";
                return RedirectToAction("Index");
            }
            ViewBag.ContactGroup = new SelectList(GetEnumSelectList<ContactGroup>(), 
                                                            "Value", "Text",model.ContactGroup);
            return View(model);
        }

        // GET: Contacts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = await _contactRepository.Get(id.Value);
            if (contact == null)
            {
                return HttpNotFound();
            }
            var contactModel = Mapper.Map<AddEditContactModel>(contact);
            return View(contactModel);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Contact contact = await _contactRepository.Get(id);
            if(contact == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            await _contactRepository.Remove(contact);

            TempData["message"] = "Contact Deleted Successfully";
            return RedirectToAction("Index");
        }
        private IEnumerable<SelectListItem> GetEnumSelectList<T>()
        {
            return (Enum.GetValues(typeof(T)).Cast<int>().Select(
                                    e => new SelectListItem()
                                    {
                                        Text = Enum.GetName(typeof(T), e),
                                        Value = e.ToString()

                                    })).ToList();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //_contactRepository.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

ContactBook.Web/Views/Contacts/Create.cshtml
@model ContactBook.Web.Models.AddEditContactModel

@{
    ViewBag.Title = "Create";
}

<h4>Create New Contact</h4>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Contact</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactGroup, "Contact Group", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10"> 
                @Html.DropDownList("ContactGroup", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContactGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ContactBook.Web/Views/Contacts/Delete.cshtml
@model ContactBook.Web.Models.AddEditContactModel

@{
    ViewBag.Title = "Delete";
}

<h4>Delete Contact</h4>

<h3>Are you sure you want to delete this?</h3>
<div>
    @*<h4>Contact</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContactGroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactGroupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ContactBook.Web/Views/Contacts/Details.cshtml
@model ContactBook.Web.Models.AddEditContactModel

@{
    ViewBag.Title = "Details";
}

<h4>Contact Details</h4>

<div>
    @*<h4>Contact</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContactGroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactGroupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ContactBook.Web/Views/Contacts/Edit.cshtml
@model ContactBook.Web.Models.AddEditContactModel

@{
    ViewBag.Title = "Edit";
}

<h4>Edit Contact</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Contact</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactGroup, "ContactGroup", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ContactGroup", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContactGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ContactBook.Web/Views/Contacts/Index.cshtml
@model IEnumerable<ContackBook.Model.Contact>

@{
    ViewBag.Title = "Index";
}

<h4>Contacts</h4>


<p>
    @Html.ActionLink("Add New Contact", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Contact Group
            @*@Html..DisplayNameFor(model => model.ContactGroupName)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateModified)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ContactGroup)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateModified)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ContactBook.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contact Book</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contact Book", "Index", "Contacts", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
<div class="container body-content">
    <h4 class="text-success">
        @{

        object msg;
        if (TempData.TryGetValue("message", out msg))
        {
            @(msg as string);
            TempData.Remove("message");
        }
    }

</h4>
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year Contack Book</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>